language: php

php:
  - 7.0
#  - 7.1
  - hhvm-3.15

dist: trusty

sudo: required

matrix:
    fast_finish: true
#    allow_failures:
#      - php: hhvm-nightly

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then composer require --dev --no-update phpunit/phpunit 6.*; else composer require --dev --no-update phpunit/phpunit ~5; fi
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'xdebug.enable = On' >> /etc/hhvm/php.ini; fi

before_script:
  - chmod 777 ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh
#  - bash tests/before.sh
  - composer install --prefer-source --no-interaction --dev --ignore-platform-reqs
  - composer dumpautoload -o

after_script:
  - kill -9 $(pgrep arangod)

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  hosts:
    - db-link